### ISSUE TITLE
myPacketSerial.send() or myPacketSerial.update() does not return an error?

### ISSUE THREAD

**Issue by Humancell** [bakercp/PacketSerial#21]
I'm debugging my current application and have found - what I think - is one of my issues.

My packets have now become larger, and are 260 bytes.  I'm now sending them and do not receive any indication that 260 bytes is too large.

On the receiving side, I am getting packets but they are only 254 bytes.

Upon digging deeper I found that the default buffer in PacketSerial is only 256 bytes.

https://github.com/bakercp/PacketSerial/blob/master/src/PacketSerial.h#L27

I'm curious if this is a "send buffer" size?  Or only a "receive buffer" size?  Or both?

It seems that there is code to catch the buffer overflow here:  https://github.com/bakercp/PacketSerial/blob/master/src/PacketSerial.h#L217

This would seem to indicate it's a receive only buffer limitation?

Is there a way that I ought to be catching this error?

**Comment by bakercp** [comment]
Hey @Humancell, I just released an updated version.

The BufferSize is the receive-buffer.  The send buffer is allocated by the Arduino.  The template parameters are documented [here](https://bakercp.github.io/PacketSerial/class_packet_serial__.html).

There was indeed a code stub for buffer overflows. Since there aren't exceptions or a generic way to send errors, I hadn't added a way to report overflows.  As of 1.3.0, I added the overflow() method that will allow you to check for overflows.  What you do with that information is up to you.  You can set an overflow LED to turn on or you can send an error message packet of your own design back to the sender.  

Anyway, I added a discussion of both of your [original template question](https://github.com/bakercp/PacketSerial/blob/master/docs/GETTING_STARTED.md#customizing-the-packetserial-class) and the new [overflow function](https://github.com/bakercp/PacketSerial/blob/master/docs/GETTING_STARTED.md#checking-for-receive-buffer-overflows) in the https://github.com/bakercp/PacketSerial/blob/master/docs/GETTING_STARTED.md doc. 

I'm closing this for now. Let me know if you have any other issues with 1.3.0.  Thanks!
